// Code generated by MockGen. DO NOT EDIT.
// Source: minecraft.go

// Package minecraft is a generated GoMock package.
package minecraft

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMinecraftServer is a mock of MinecraftServer interface.
type MockMinecraftServer struct {
	ctrl     *gomock.Controller
	recorder *MockMinecraftServerMockRecorder
}

// MockMinecraftServerMockRecorder is the mock recorder for MockMinecraftServer.
type MockMinecraftServerMockRecorder struct {
	mock *MockMinecraftServer
}

// NewMockMinecraftServer creates a new mock instance.
func NewMockMinecraftServer(ctrl *gomock.Controller) *MockMinecraftServer {
	mock := &MockMinecraftServer{ctrl: ctrl}
	mock.recorder = &MockMinecraftServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinecraftServer) EXPECT() *MockMinecraftServerMockRecorder {
	return m.recorder
}

// PutCommand mocks base method.
func (m *MockMinecraftServer) PutCommand(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutCommand", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutCommand indicates an expected call of PutCommand.
func (mr *MockMinecraftServerMockRecorder) PutCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutCommand", reflect.TypeOf((*MockMinecraftServer)(nil).PutCommand), cmd)
}

// Start mocks base method.
func (m *MockMinecraftServer) Start() (chan string, chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(chan string)
	ret1, _ := ret[1].(chan string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Start indicates an expected call of Start.
func (mr *MockMinecraftServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMinecraftServer)(nil).Start))
}

// Stop mocks base method.
func (m *MockMinecraftServer) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockMinecraftServerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMinecraftServer)(nil).Stop))
}
